-- Penduline — retrait de l'épinglage.
--
-- POURQUOI IL DISPARAÎT.
--
-- Épingler hissait une tâche en tête de SA case, avec un fanion. Trois raisons
-- de s'en séparer :
--
--   1. La case a déjà un ordre manuel — glisser-déposer et `Alt`+↑/↓. L'épinglage
--      était donc un second mécanisme d'ordre, plus grossier, posé sur un premier
--      plus fin.
--   2. C'était une priorité SUR une priorité : « Faire » signifie déjà urgent et
--      important ; hiérarchiser à l'intérieur redouble ce que la case dit déjà.
--   3. Rien ne le faisait jamais retomber. Aucune expiration, aucun rappel — le
--      scénario connu où tout finit épinglé et où le fanion ne veut plus rien
--      dire. #47 n'avait d'ailleurs pas de signal pour les épinglages qui dorment.
--
-- Et le mode « aujourd'hui » (#49) sert désormais la vraie intention — « qu'est-ce
-- que je fais maintenant » — avec une mécanique qui, elle, expire toute seule et
-- se limite à trois.
--
-- ⚠️ LA COLONNE EST SUPPRIMÉE, ET C'EST IRRÉVERSIBLE.
--
-- Les épinglages existants sont perdus. C'est assumé : ce sont des drapeaux
-- booléens sur une fonctionnalité qu'on retire, pas du contenu utilisateur —
-- aucune tâche, aucun titre, aucun lien ne disparaît. Le seul effet visible est
-- que les tâches jusque-là hissées en tête retrouvent leur rang dans l'ordre
-- manuel de leur case, qu'elles n'avaient jamais quitté.
--
-- ⚠️ NE PAS APPLIQUER AVANT QUE L'EXTENSION SANS `pinned` SOIT DIFFUSÉE.
--
-- Ce paragraphe disait l'inverse, et il avait tort. Il affirmait qu'un client
-- lisant encore `pinned` recevrait `undefined` et non une erreur, donc que la
-- fenêtre entre les migrations et le frontend était sans danger. Vérifié contre
-- la production, c'est faux :
--
--   GET /rest/v1/tasks?select=id,title,pinned
--   → HTTP 400  {"code":"42703","message":"column tasks.pinned does not exist"}
--
-- Le raisonnement ne vaudrait que pour un `select *`. Or aucun client n'en fait :
-- tous NOMMENT leurs colonnes une par une (`store.ts`, `useFocus.ts`, et le même
-- motif dans l'extension). Une colonne absente d'une liste explicite n'est pas
-- ignorée, elle casse la requête — donc TOUTE lecture de tâches, pas seulement
-- le tri et la décoration.
--
-- Pour le front web, la fenêtre reste courte : le déploiement qui applique cette
-- migration sert le nouveau bundle quelques minutes plus tard. L'EXTENSION, elle,
-- ne suit pas ce rythme — elle vit chez les utilisateurs, et une version
-- corrective doit passer la revue du Chrome Web Store puis être diffusée par
-- Chrome. Des jours, pas des minutes. Appliquer cette migration pendant que la
-- version en ligne réclame encore `pinned` met l'extension à 400 sur chaque
-- lecture, pour tous ses utilisateurs, sans recours.
--
-- Préalable, donc : extension **1.5.0 ou plus** publiée ET diffusée. Le paquet
-- 1.4.0 est le dernier à demander `pinned` — voir work/publication-extension.md.
alter table public.tasks
  drop column pinned;
